### ISSUE TITLE
Orderless search

### ISSUE THREAD

**Issue by djrothblatt** [zack/citibike#30]
This is a great project! I can see myself showing this to people in my life.

# Orderless search
The dock search bar only shows *exact* matches, which is a problem when you aren't totally sure what the name of the dock is.
## Example
(Normally I would provide screenshots/gifs, but I'm having trouble with that today. So prose only. My apologies!)
I want to find stations along Amsterdam Avenue in Manhattan, so I type "Amsterdam Ave" into the search bar and get relevant results. So far so good.
Next, I decide I specifically want to see info about the dock on Amsterdam and 104th. So I add "104", making the search term "Amsterdam Ave 104". No options!
If you clear the search term and type "104 &", also no options!
If you clear the search term again and type "104 st &", _now_ you see options.
## Expected behavior
Typing "Amsterdam Ave 104" into the search bar would show results that match "Amsterdam", "Ave", and "104".
## Actual behavior
Typing "Amsterdam Ave 104" into the search bar shows no results because the station is actually called "W 104 St & Amsterdam Ave"
## Coding this
I haven't dug into the codebase yet, but my sketch of the code for this feature would look something like this:
```typescript
const isMatch = term => dockName => term.split(' ').every(word => dockName.includes(word));
const autocompleteCandidates = docks.filter(isMatch(term));
```

Thanks again for this project! I'm happy to make a PR for this if you think this is a good feature to implement.

**Comment by zack** [comment]
Great idea, thank you :)

**Comment by zack** [comment]
Ah dang, this is what I get for trying to rush work on my lunch break. I see now that I didn't address the whole issue. Will reopen to track more work.

**Comment by zack** [comment]
Alright, got it now. :)

**Comment by djrothblatt** [comment]
I just tried it out. Perfect! Exactly what I wanted. Thanks so much!
